name: Build and Push Docker Images, Create SageMaker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      PREPROCESSING_DOCKERFILE: Dockerfile.preprocessing
      TRAINING_DOCKERFILE: Dockerfile.training
      MODEL_REGISTRY_DOCKERFILE: Dockerfile.model_registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS Account ID
        id: get_account_id
        run: echo "::set-output name=account_id::$(aws sts get-caller-identity --query Account --output text)"
      
      - name: Set ECR Repository Names
        id: set_repo_names
        run: |
          echo "::set-output name=preprocessing_name::demo-sagemaker-multimodel-preprocessing"
          echo "::set-output name=training_name::demo-sagemaker-multimodel-training"
          echo "::set-output name=model_registry_name::demo-sagemaker-multimodel-model-registry"

      - name: Ensure ECR Repositories Exist
        run: |
          aws ecr describe-repositories --repository-names "${{ steps.set_repo_names.outputs.preprocessing_name }}" --region ${{ env.AWS_REGION }} || \
          aws ecr create-repository --repository-name "${{ steps.set_repo_names.outputs.preprocessing_name }}" --region ${{ env.AWS_REGION }}

          aws ecr describe-repositories --repository-names "${{ steps.set_repo_names.outputs.training_name }}" --region ${{ env.AWS_REGION }} || \
          aws ecr create-repository --repository-name "${{ steps.set_repo_names.outputs.training_name }}" --region ${{ env.AWS_REGION }}

          aws ecr describe-repositories --repository-names "${{ steps.set_repo_names.outputs.model_registry_name }}" --region ${{ env.AWS_REGION }} || \
          aws ecr create-repository --repository-name "${{ steps.set_repo_names.outputs.model_registry_name }}" --region ${{ env.AWS_REGION }}

      - name: Authenticate Docker to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.get_account_id.outputs.account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and Push Preprocessing Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ steps.get_account_id.outputs.account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ steps.set_repo_names.outputs.preprocessing_name }}:latest \
            -f ${{ env.PREPROCESSING_DOCKERFILE }} --push .

      - name: Build and Push Training Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ steps.get_account_id.outputs.account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ steps.set_repo_names.outputs.training_name }}:latest \
            -f ${{ env.TRAINING_DOCKERFILE }} --push .

      - name: Build and Push Model Registry Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ steps.get_account_id.outputs.account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ steps.set_repo_names.outputs.model_registry_name }}:latest \
            -f ${{ env.MODEL_REGISTRY_DOCKERFILE }} --push .

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install sagemaker==2.227.0
          pip install -r requirements.txt

      - name: Create SageMaker Pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          python create_sagemaker_pipeline.py
